global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: load-balancer
    static_configs:
      - targets: [load-balancer:8000]
    metrics_path: /metrics

  - job_name: master
    static_configs:
      - targets: [master:8001]
    metrics_path: /metrics

  - job_name: rag-retriever
    static_configs:
      - targets: [rag-retriever:8002]
    metrics_path: /metrics

  - job_name: ingestion-service
    static_configs:
      - targets: [ingestion-service:8003]
    metrics_path: /metrics
